In [55]:
import numpy as np
import pandas as pd

Load the dataset

In [56]:
df = pd.read_csv('Creditcard_data.csv')
print(df.shape)

df.head()

(772, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [57]:
# Drop the Time column as it is not required for the analysis
df.drop('Time', axis=1, inplace=True)
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [58]:
df['Class'].value_counts()
# The dataset is imbalance dataset because the number of zero class is much more than the number of one class. so we have to convert it into balanced dataset first.

0    763
1      9
Name: Class, dtype: int64

Balancing the dataset

In [59]:
X = df.drop('Class', axis=1)
Y = df['Class']

In [60]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [61]:
test_df = pd.concat([X_test, y_test], axis=1)

In [67]:
# Balancing the dataset using overfitting technique i.e. SMOTE
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=0)
X, Y = sm.fit_resample(X_train, y_train)
X.shape, Y.shape

((1218, 29), (1218,))

In [63]:
Y.value_counts()

0    609
1    609
Name: Class, dtype: int64

In [64]:
# Generating the balanced dataset
df = pd.concat([X, Y], axis=1)

In [65]:
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,1.063195,-1.156247,-0.814094,-0.462132,1.137835,3.909057,-1.116745,0.920514,-0.600150,0.686100,...,-0.205083,-0.434832,-0.220055,0.991996,0.631624,-0.223179,0.052542,0.053525,158.00,0
1,1.254258,1.218376,-2.148615,1.155957,1.813892,-0.238358,0.623888,-0.060265,-0.739258,-1.448114,...,-0.210083,-0.463849,-0.370852,-1.644707,0.962670,-0.200548,0.055746,0.071654,2.95,0
2,-0.997176,0.228365,1.715340,-0.420067,0.560838,0.564725,0.846047,0.197491,-0.097202,-0.439347,...,-0.070241,0.015445,0.072651,-0.272272,-0.087682,0.138132,0.125902,-0.063022,86.43,0
3,-1.428535,1.793578,0.545758,-0.399309,0.673577,0.745919,-0.358475,-4.044724,0.232362,-0.081320,...,3.844729,-1.093705,0.256804,-0.869687,0.252491,-0.452726,0.055281,-0.153211,2.29,0
4,1.027114,-1.272543,0.673656,-0.747436,-1.299107,0.293656,-1.054200,0.234900,-0.574991,0.680726,...,0.522113,1.101912,-0.248747,-0.259414,0.296058,-0.030996,0.018465,0.033482,159.00,0

In [66]:
df.tail()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1213,0.926095,0.406160,0.344070,0.532201,-0.039034,-0.702383,0.145101,-0.107556,-0.008878,-0.243652,...,-0.243385,-0.707227,0.134465,-0.134671,-0.230775,0.089334,0.047648,0.086356,2.216847,1
1214,0.649727,-0.178735,0.704893,0.776199,0.155267,-0.760826,-0.321629,-0.018577,0.206859,-0.291171,...,-0.155597,-0.455667,0.159640,0.116994,0.135029,0.237160,-0.042180,-0.006651,2.468782,1
1215,-2.141151,-0.937534,1.156641,0.251947,1.056107,-0.530263,0.286510,0.076334,-0.067361,-0.304618,...,0.079971,0.001547,0.243383,-0.254853,-0.145368,0.121342,-0.316638,-0.254204,163.883719,1
1216,-1.650316,0.090361,1.247398,-0.565247,0.925607,-0.358134,0.335507,0.108263,0.005432,-0.121770,...,-0.152766,-0.140479,-0.261453,-0.169645,-0.255959,0.164724,-0.318918,-0.355488,1.000000,1
1217,1.256977,0.360914,0.305749,0.691294,-0.361412,-1.068216,0.092289,-0.208325,0.019933,-0.285114,...,-0.287051,-0.823840,0.127774,0.342148,0.219750,0.094474,-0.022497,0.030930,1.660509,1

## Sampling Techniques & Applying of models

Simple Random Sampling

n = (Z^2 * p * (1-p)) / E^2

In [69]:
import math
import random

n = (1.96**2 * 0.5 * 0.5) / (0.05**2)
n = math.ceil(n)
print(n)

X_sample = X.sample(n=n, random_state=42)
print(X_sample.shape)

y_sample = Y[X_sample.index]
print(y_sample.shape)

385
(385, 29)
(385,)

In [70]:
X_sample.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
541,1.260248,-0.020172,-1.164387,0.266251,2.184886,3.607421,-0.436997,0.848745,0.172271,-0.019013,...,-0.035543,-0.182469,-0.481653,-0.128006,1.009959,0.892621,-0.326798,0.025039,0.012735,9.990000
259,-2.421230,-1.369602,2.261281,2.011034,1.878525,-1.275607,-1.251029,0.212619,0.142608,0.000982,...,-0.411785,-0.089577,0.157737,-0.624865,0.487156,0.270894,-0.093370,0.330056,-0.056340,24.000000
43,1.190844,-0.608427,0.069097,-0.493509,-0.944775,-1.390857,0.047659,-0.467884,-1.248877,0.570878,...,0.374268,0.262280,0.489143,-0.186645,0.797721,0.630575,-0.183914,-0.029302,0.033508,127.690000
1008,-0.459365,-0.231668,0.969644,0.378326,1.244049,0.339547,-0.321952,0.306197,0.154898,-0.190407,...,0.126883,0.012857,0.023309,0.188733,-1.233746,-1.088549,0.277248,0.140192,0.127088,1.121027
584,-0.753769,1.098287,1.835453,0.614571,-0.317859,-0.101055,0.039454,-0.656824,-0.048761,-0.216191,...,-0.369512,1.101142,0.686059,0.005954,0.361744,-0.457852,-0.352576,0.094602,0.170480,5.000000

In [71]:
y_sample.head()

541     0
259     0
43      0
1008    1
584     0
Name: Class, dtype: int64

In [77]:
# Applying various models on this random sample
# logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

lr = LogisticRegression()
lr.fit(X_sample, y_sample)
y_pred = lr.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.8838709677419355

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [73]:
# naive bayes
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_sample, y_sample)
y_pred = nb.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7806451612903226

In [74]:
# random forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_sample, y_sample)
y_pred = rf.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.9741935483870968

In [75]:
# decision tree
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_sample, y_sample)
y_pred = dt.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.9290322580645162

In [76]:
# knn
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_sample, y_sample)
y_pred = knn.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.864516129032258

Stratified Sampling

n = (Z^2 * p * (1-p)) / (E/S)^2

In [81]:
# Stratified Sampling
df = pd.concat([X, Y], axis=1)
# df['Class'].value_counts()
stratified_df = df.groupby('Class').apply(lambda x: x.sample(frac=0.05, random_state=42))
print(stratified_df['Class'].value_counts())

X_stratified = stratified_df.drop('Class', axis=1)
y_stratified = stratified_df['Class']

0    30
1    30
Name: Class, dtype: int64

In [82]:
X_stratified.shape, y_stratified.shape

((60, 29), (60,))

In [84]:
X_stratified.head()

                 V1        V2        V3        V4        V5        V6  \
Class
0     292  1.248022  0.367821  0.058192  0.933295  0.443929  0.226403
      367  1.121785  0.206367  0.529086  1.318229 -0.161515  0.024067
      472 -0.528218  0.981232  1.652988 -0.150715  0.137048 -0.203980
      573  1.057021 -0.646956  0.729167 -0.569262 -1.174307 -0.527625
      119 -2.395434 -1.545369  1.919391  1.062514 -0.627806  1.154561

                 V7        V8        V9       V10  ...       V20       V21  \
Class                                              ...
0     292  0.115654 -0.059580 -0.155528 -0.033506  ... -0.037650 -0.075303
      367 -0.020503  0.103401 -0.023411  0.039351  ... -0.183745 -0.037897
      472  0.583370  0.165246 -0.781696 -0.211147  ...  0.127768 -0.123569
      573 -0.471677  0.051744  1.904018 -1.176609  ... -0.070137  0.186184
      119 -0.861501  1.089486 -1.341268  0.200626  ...  0.561230 -0.120569

                V22       V23       V24       V25       V26       V27  \
Class
0     292 -0.098561 -0.137178 -0.940903  0.645500 -0.334234  0.044271
      367  0.121195 -0.046623  0.239376  0.617560 -0.342429  0.039618
      472 -0.272731  0.023887  0.223936 -0.297777  0.068300  0.281018
      573  0.743093 -0.163619  0.453570  0.615479 -0.508562  0.089553
      119 -0.473853  0.453082 -0.323900  0.105117 -0.219200  0.261789

                V28  Amount
Class
0     292  0.015850   10.00
      367  0.007107    1.00
      472  0.111557    6.99
      573  0.037617   69.00
      119 -0.122954  231.71

[5 rows x 29 columns]

In [85]:
X_stratified.tail()

                  V1        V2        V3        V4        V5        V6  \
Class
1     919  -0.386590 -0.124771  0.898932  0.342358  1.186537  0.327519
      713  -0.288992  0.018587  0.804101  0.294121  1.109409  0.311389
      1108  0.095638 -0.586820  0.518073  1.122375  0.106255 -1.066763
      944   0.809039  0.426050  0.358873  0.474917  0.079311 -0.571424
      377  -1.738582  0.052740  1.187057 -0.656652  0.920623 -0.291788

                  V7        V8        V9       V10  ...       V20       V21  \
Class                                               ...
1     919  -0.237512  0.283430  0.116937 -0.183880  ...  0.103556 -0.006484
      713  -0.124270  0.252898  0.066029 -0.175127  ...  0.072272 -0.032422
      1108  0.156763 -0.171799 -0.062654 -0.435303  ...  0.514148 -0.030584
      944   0.165862 -0.073637 -0.024553 -0.229780  ... -0.066231 -0.227647
      377   0.269083  0.140631  0.023464 -0.066407  ...  0.002974 -0.179545

                 V22       V23       V24       V25       V26       V27  \
Class
1     919  -0.032037  0.183582 -1.251531 -1.129594  0.249682  0.152696
      713  -0.106260  0.176672 -1.275382 -1.184638  0.212714  0.169466
      1108 -0.481285  0.464920  0.171047  0.236973  0.029617 -0.084486
      944  -0.662566  0.136736 -0.303445 -0.389802  0.087423  0.072924
      377  -0.192036 -0.261879 -0.237477 -0.335040  0.240323 -0.345129

                 V28      Amount
Class
1     919   0.141167    1.103132
      713   0.160047    1.079134
      1108  0.032246  143.862658
      944   0.106101    2.048409
      377  -0.383563    1.000000

[5 rows x 29 columns]

In [100]:
# logistic regression

lr = LogisticRegression()
lr.fit(X_stratified, y_stratified)
y_pred = lr.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.864516129032258

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [87]:
# naive bayes

nb = GaussianNB()
nb.fit(X_stratified, y_stratified)
y_pred = nb.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7354838709677419

In [88]:
# random forest

rf = RandomForestClassifier()
rf.fit(X_stratified, y_stratified)
y_pred = rf.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.8709677419354839

In [89]:
# decision tree

dt = DecisionTreeClassifier()
dt.fit(X_stratified, y_stratified)
y_pred = dt.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7354838709677419

In [90]:
# knn

knn = KNeighborsClassifier()
knn.fit(X_stratified, y_stratified)
y_pred = knn.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7548387096774194

Cluster Sampling

n = (Z^2 * p * (1-p)) / (E/C)^2

In [94]:
# Cluster Sampling

# defining variables

length = len(df)
groups = 5
size = length / groups
print(size)

243.6

In [95]:
# group list creation

group_list = []
group_id = 0
size_count = 0

for i in range(length):
    if size_count < size:
        group_list.append(group_id)
        size_count += 1
    else:
        group_id += 1
        group_list.append(group_id)
        size_count = 1

df['group'] = group_list
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,group
0,1.063195,-1.156247,-0.814094,-0.462132,1.137835,3.909057,-1.116745,0.920514,-0.600150,0.686100,...,-0.434832,-0.220055,0.991996,0.631624,-0.223179,0.052542,0.053525,158.00,0,0
1,1.254258,1.218376,-2.148615,1.155957,1.813892,-0.238358,0.623888,-0.060265,-0.739258,-1.448114,...,-0.463849,-0.370852,-1.644707,0.962670,-0.200548,0.055746,0.071654,2.95,0,0
2,-0.997176,0.228365,1.715340,-0.420067,0.560838,0.564725,0.846047,0.197491,-0.097202,-0.439347,...,0.015445,0.072651,-0.272272,-0.087682,0.138132,0.125902,-0.063022,86.43,0,0
3,-1.428535,1.793578,0.545758,-0.399309,0.673577,0.745919,-0.358475,-4.044724,0.232362,-0.081320,...,-1.093705,0.256804,-0.869687,0.252491,-0.452726,0.055281,-0.153211,2.29,0,0
4,1.027114,-1.272543,0.673656,-0.747436,-1.299107,0.293656,-1.054200,0.234900,-0.574991,0.680726,...,1.101912,-0.248747,-0.259414,0.296058,-0.030996,0.018465,0.033482,159.00,0,0

In [96]:
# allocating the elements in their respective groups randomly

df['group'] = df['group'].apply(lambda x: random.randint(0, groups-1))
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,group
0,1.063195,-1.156247,-0.814094,-0.462132,1.137835,3.909057,-1.116745,0.920514,-0.600150,0.686100,...,-0.434832,-0.220055,0.991996,0.631624,-0.223179,0.052542,0.053525,158.00,0,1
1,1.254258,1.218376,-2.148615,1.155957,1.813892,-0.238358,0.623888,-0.060265,-0.739258,-1.448114,...,-0.463849,-0.370852,-1.644707,0.962670,-0.200548,0.055746,0.071654,2.95,0,1
2,-0.997176,0.228365,1.715340,-0.420067,0.560838,0.564725,0.846047,0.197491,-0.097202,-0.439347,...,0.015445,0.072651,-0.272272,-0.087682,0.138132,0.125902,-0.063022,86.43,0,3
3,-1.428535,1.793578,0.545758,-0.399309,0.673577,0.745919,-0.358475,-4.044724,0.232362,-0.081320,...,-1.093705,0.256804,-0.869687,0.252491,-0.452726,0.055281,-0.153211,2.29,0,4
4,1.027114,-1.272543,0.673656,-0.747436,-1.299107,0.293656,-1.054200,0.234900,-0.574991,0.680726,...,1.101912,-0.248747,-0.259414,0.296058,-0.030996,0.018465,0.033482,159.00,0,1

In [97]:
# randomnly choosing the group

group = random.randint(0, groups-1)
print(group)

2

In [108]:
# Defining the clustered sample

clustered_df = df[df['group'] == group]
print(clustered_df.shape)

# clustered_df.head()
#Drop the group column
clustered_df = clustered_df.drop('group', axis=1)
clustered_df.head()

X_clustered = clustered_df.drop('Class', axis=1)
y_clustered = clustered_df['Class']

X_clustered.shape, y_clustered.shape

(216, 31)

((216, 29), (216,))

In [109]:
# logistic regression

lr = LogisticRegression()
lr.fit(X_clustered, y_clustered)
y_pred = lr.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.8516129032258064

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [110]:
# naive bayes

nb = GaussianNB()
nb.fit(X_clustered, y_clustered)
y_pred = nb.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7935483870967742

In [111]:
# random forest

rf = RandomForestClassifier()
rf.fit(X_clustered, y_clustered)
y_pred = rf.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.9741935483870968

In [112]:
# decision tree

dt = DecisionTreeClassifier()
dt.fit(X_clustered, y_clustered)
y_pred = dt.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.8516129032258064

In [113]:
# knn

knn = KNeighborsClassifier()
knn.fit(X_clustered, y_clustered)
y_pred = knn.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.7225806451612903

In [128]:
# Drop the group column
df = df.drop('group', axis=1)
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,1.063195,-1.156247,-0.814094,-0.462132,1.137835,3.909057,-1.116745,0.920514,-0.600150,0.686100,...,-0.205083,-0.434832,-0.220055,0.991996,0.631624,-0.223179,0.052542,0.053525,158.00,0
1,1.254258,1.218376,-2.148615,1.155957,1.813892,-0.238358,0.623888,-0.060265,-0.739258,-1.448114,...,-0.210083,-0.463849,-0.370852,-1.644707,0.962670,-0.200548,0.055746,0.071654,2.95,0
2,-0.997176,0.228365,1.715340,-0.420067,0.560838,0.564725,0.846047,0.197491,-0.097202,-0.439347,...,-0.070241,0.015445,0.072651,-0.272272,-0.087682,0.138132,0.125902,-0.063022,86.43,0
3,-1.428535,1.793578,0.545758,-0.399309,0.673577,0.745919,-0.358475,-4.044724,0.232362,-0.081320,...,3.844729,-1.093705,0.256804,-0.869687,0.252491,-0.452726,0.055281,-0.153211,2.29,0
4,1.027114,-1.272543,0.673656,-0.747436,-1.299107,0.293656,-1.054200,0.234900,-0.574991,0.680726,...,0.522113,1.101912,-0.248747,-0.259414,0.296058,-0.030996,0.018465,0.033482,159.00,0

Systematic Sampling

In [129]:
# Systematic Sampling

# get interval value

n = (1.96**2 * 0.5 * 0.5) / (0.05**2)
# n = math.ceil(n)
length = len(df)
interval = length / n
print(interval)

3.170553935860059

In [130]:
# get the starting index

start = np.random.randint(0, interval)

In [131]:
systematic_sample = df.iloc[start::int(interval)] 

systematic_sample.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1,1.254258,1.218376,-2.148615,1.155957,1.813892,-0.238358,0.623888,-0.060265,-0.739258,-1.448114,...,-0.210083,-0.463849,-0.370852,-1.644707,0.962670,-0.200548,0.055746,0.071654,2.95,0
4,1.027114,-1.272543,0.673656,-0.747436,-1.299107,0.293656,-1.054200,0.234900,-0.574991,0.680726,...,0.522113,1.101912,-0.248747,-0.259414,0.296058,-0.030996,0.018465,0.033482,159.00,0
7,1.211406,0.007850,0.950798,1.137646,-0.495189,0.301371,-0.518350,0.095426,0.817592,-0.226339,...,-0.107248,-0.057153,-0.118933,-0.421241,0.556146,-0.360164,0.076930,0.031800,9.99,0
10,-0.653445,0.160225,1.592256,1.296832,0.997175,-0.343000,0.469937,-0.132470,-0.197794,-0.105006,...,0.038363,0.336449,-0.014883,0.102959,-0.265322,-0.348637,0.011238,-0.049478,19.85,0
13,1.120599,-0.313308,0.395309,0.596756,-0.420412,0.325862,-0.404105,0.283071,0.630035,-0.066353,...,-0.039016,0.005732,-0.108844,-0.283233,0.441306,0.579529,-0.026439,-0.007082,29.95,0

In [132]:
X_systematic = systematic_sample.drop('Class', axis=1)
y_systematic = systematic_sample['Class']

In [133]:
# logistic regression

lr = LogisticRegression()
lr.fit(X_systematic, y_systematic)
y_pred = lr.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.8516129032258064

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [134]:
# naive bayes

nb = GaussianNB()
nb.fit(X_systematic, y_systematic)
y_pred = nb.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.4838709677419355

In [135]:
# random forest

rf = RandomForestClassifier()
rf.fit(X_systematic, y_systematic)
y_pred = rf.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.9741935483870968

In [136]:
# decision tree

dt = DecisionTreeClassifier()
dt.fit(X_systematic, y_systematic)
y_pred = dt.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.9548387096774194

In [137]:
# knn

knn = KNeighborsClassifier()
knn.fit(X_systematic, y_systematic)
y_pred = knn.predict(X_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

Accuracy Score:  0.832258064516129

In [145]:
# Summarize the accuracy of all the models for all the sampling techniques

sampling_techniques = ['Random Sampling', 'Stratified Sampling', 'Cluster Sampling', 'Systematic Sampling']
accuracy_scores = [[0.8839, 0.7806, 0.9742, 0.9290, 0.8645], [0.8645, 0.7355, 0.8710, 0.7355, 0.7548], [0.8516, 0.7935, 0.9742, 0.8516, 0.7226], [0.8516, 0.4839, 0.9742, 0.9548, 0.8322]]
for i in range(4):
    print('\nSampling Technique: ', sampling_techniques[i])
    print('Logistic Regression: ', accuracy_scores[i][0])
    print('Naive Bayes: ', accuracy_scores[i][1])
    print('Random Forest: ', accuracy_scores[i][2])
    print('Decision Tree: ', accuracy_scores[i][3])
    print('KNN: ', accuracy_scores[i][4])

Sampling Technique:  Random Sampling
Logistic Regression:  0.8839
Naive Bayes:  0.7806
Random Forest:  0.9742
Decision Tree:  0.929
KNN:  0.8645

Sampling Technique:  Stratified Sampling
Logistic Regression:  0.8645
Naive Bayes:  0.7355
Random Forest:  0.871
Decision Tree:  0.7355
KNN:  0.7548

Sampling Technique:  Cluster Sampling
Logistic Regression:  0.8516
Naive Bayes:  0.7935
Random Forest:  0.9742
Decision Tree:  0.8516
KNN:  0.7226

Sampling Technique:  Systematic Sampling
Logistic Regression:  0.8516
Naive Bayes:  0.4839
Random Forest:  0.9742
Decision Tree:  0.9548
KNN:  0.8322